/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2f1400",
        "tertiary-container": "#f7a564",
        "on-secondary-fixed-variant": "#1f3ba6",
        "primary-fixed": "#7ef9cd",
        "on-primary": "#003829",
        "error": "#ffb4ab",
        "inverse-primary": "#006c51",
        "surface-container-low": "#151b2a",
        "background": "#0c1321",
        "coral-red": "#FF5F5F",
        "danger-bg": "#1A0B0B",
        "error-container": "#93000a",
        "outline-variant": "#3d4a44",
        "on-tertiary": "#4e2600",
        "on-error": "#690005",
        "primary": "#6de9be",
        "secondary-fixed-dim": "#b9c3ff",
        "on-secondary-container": "#a1b1ff",
        "surface-dim": "#0c1321",
        "secondary-container": "#1f3ba6",
        "outline": "#86948d",
        "tertiary-fixed": "#ffdcc4",
        "primary-fixed-dim": "#60dcb2",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#00513c",
        "tertiary": "#ffc8a1",
        "on-surface": "#dce2f6",
        "secondary": "#b9c3ff",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-lowest": "#070e1c",
        "surface-variant": "#2e3544",
        "on-primary-container": "#00533e",
        "surface-bright": "#323949",
        "surface-container": "#19202e",
        "on-secondary-fixed": "#001356",
        "secondary-fixed": "#dde1ff",
        "on-background": "#dce2f6",
        "primary-container": "#4ecca3",
        "tertiary-fixed-dim": "#ffb780",
        "inverse-on-surface": "#2a3040",
        "surface-container-highest": "#2e3544",
        "on-tertiary-container": "#723900",
        "inverse-surface": "#dce2f6",
        "on-error-container": "#ffdad6",
        "on-secondary": "#002388",
        "surface": "#0c1321",
        "surface-container-high": "#232a39",
        "surface-tint": "#60dcb2",
        "on-surface-variant": "#bccac2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "20px",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "container-margin": "20px",
        "sm": "12px",
        "gutter": "16px",
        "base": "4px",
        "2xl": "48px",
        "xs": "8px",
        "element-gap": "16px",
        "container-padding": "20px",
        "section-margin": "40px",
        "stack-margin": "24px"
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "stats-xl": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "label-md": ["Manrope"],
        "label-sm": ["Manrope"],
        "body-md": ["Manrope"],
        "label-caps": ["Manrope"],
        "stats-numeral": ["Manrope"],
        "display-hero": ["Manrope"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "stats-xl": ["36px", { "lineHeight": "44px", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "stats-numeral": ["20px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-hero": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "800" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}
